'use strict';

export default {
  GET_DATA_REQUEST: 'GET_DATA_REQUEST',
  GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
  GET_DATA_FAILURE: 'GET_DATA_FAILURE',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_REMOTE_SUCCESS: 'GET_USER_REMOTE_SUCCESS',
  GET_USER_REMOTE_FAILURE: 'GET_USER_REMOTE_FAILURE',
};